function Convert-CurlToPowerShell {
    <#
    .SYNOPSIS
    Converts a cURL command (processed by Curl2PS) into a PowerShell script using Invoke-RestMethod.

    .DESCRIPTION
    This function works in conjunction with the Curl2PS module to convert a cURL command into a PowerShell script.
    The Curl2PS module parses the raw cURL string into a structured PowerShell object (`CurlObject`), which this
    function then processes to generate a PowerShell script that replicates the HTTP request using `Invoke-RestMethod`.

    .PARAMETER CurlObject
    A PowerShell object generated by the Curl2PS module. It must include properties such as `Uri`, `Method`, `Headers`,
    and optionally `Body`.

    .EXAMPLE
    # Example usage with Curl2PS:
    $curlString = @"
    curl 'https://example.com/api' \
    -H 'Authorization: Bearer token' \
    -H 'Content-Type: application/json' \
    --data-raw '{"key":"value"}'
    "@

    # Convert the cURL string into a PowerShell object using Curl2PS
    $curlObject = Invoke-Curl2PS -CurlString $curlString

    # Generate the PowerShell script
    $generatedScript = Convert-CurlToPowerShell -CurlObject $curlObject

    # Output the generated script
    Write-Output $generatedScript

    .NOTES
    - This function assumes that the Curl2PS module is installed and available in the session.
    - The `Body` property of the CurlObject is expected to be in JSON format.
    - The generated script uses a splatting approach for readability and maintainability.

    #>
    param (
        [Parameter(Mandatory)]
        [PSCustomObject]$CurlObject
    )

    $uri = $CurlObject.Uri
    $headers = @{
        'Authorization' = "Bearer `$token"
        'Content-Type'  = $CurlObject.ContentType -join ", "
    }

    $method = $CurlObject.Method

    $psObject = $curlObject.Body | ConvertFrom-Json
    # Format the requests array dynamically
    $requests = $psObject.requests | ForEach-Object {
        $headersPart = if ($_.headers) { "'headers' = $($_.headers | ConvertTo-Json -Depth 10)" } else { $null }
        $bodyPart = if ($_.body) { "'body' = $($_.body | ConvertTo-Json -Depth 10)" } else { $null }
        @"
        @{
            "id" = "$($_.id)"
            "url" = "$($_.url)"
            "method" = "$($_.method)"$(if ($headersPart) { "`n        $headersPart" }) $(if ($bodyPart) { "`n        $bodyPart" })
        }
"@
    }

    # Join the requests without a trailing comma
    $requestsFormatted = ($requests -join ",`n")

    # Build the body
    $body = @"
@{
    requests = @(
$requestsFormatted
    )
}
"@



    $psCode = @"
`$uri = '$uri'
`$method = '$method'

`$token = ''

`$headers = @{
    'Authorization' = '$($headers['Authorization'])'
    'Content-Type'  = '$($headers['Content-Type'])'
}

`$body = $body


`$splat = @{
    Uri     = `$uri
    Method  = `$method
    Headers = `$headers
    Body    = `$body
}

Invoke-RestMethod @splat
"@

    return $psCode
}

# PSGallery: https://www.powershellgallery.com/packages/Curl2PS
# GitHub: https://github.com/ThePoShWolf/Curl2PS
# Install-Module -Name Curl2PS -Scope CurrentUser


$curlString = @"
curl 'https://graph.microsoft.com/beta/`$batch' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,da;q=0.8' \
  -H 'authorization: Bearer REDACTED' \
  -H 'client-request-id: 0be979e5-76dc-4c28-8af0-2c0851ad6502' \
  -H 'content-type: application/json' \
  -H 'dnt: 1' \
  -H 'origin: https://sandbox-2.reactblade.portal.azure.net' \
  -H 'priority: u=1, i' \
  -H 'referer: https://sandbox-2.reactblade.portal.azure.net/' \
  -H 'sec-ch-ua: "Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36' \
  -H 'x-ms-client-request-id: 0be979e5-76dc-4c28-8af0-2c0851ad6502' \
  -H 'x-ms-client-session-id: a6275cffec774651a4b64016f8f22088' \
  -H 'x-ms-command-name: Common - AutoBatch' \
  --data-raw '{"requests":[{"id":"96cd24f3-a35a-481e-8276-efe870baa887","method":"GET","url":"/users?`$select=id,displayName,userType,onPremisesSyncEnabled,companyName,creationType&`$top=40&`$orderby=displayName asc&`$count=true","headers":{"ConsistencyLevel":"eventual","x-ms-command-name":"UserManagement - ListUsers","x-ms-client-request-id":"3e80893e-234d-4d60-b723-eda8791a1a13","client-request-id":"3e80893e-234d-4d60-b723-eda8791a1a13","x-ms-client-session-id":"a6275cffec774651a4b64016f8f22088"}}]}'
"@

$curlObject = Invoke-Curl2PS -CurlString $curlString
$generatedScript = Convert-CurlToPowerShell -CurlObject $curlObject
$generatedScript

$curlString2 = @"
curl 'https://graph.microsoft.com/beta/`$batch' \
  -H 'content-type: application/json' \
  --data-raw '{"requests":[{"headers":{"Content-Type":"application/json"},"body":{"addLicenses":[{"skuId":"05e9a617-0261-4cee-bb44-138d3ef5d965"}],"removeLicenses":[]},"method":"POST","id":"1","url":"/users/`$userId/assignLicense"},{"body":{"@odata.id":"https://graph.microsoft.com/v1.0/users/`$userId"},"method":"POST","headers":{"Content-Type":"application/json"},"dependsOn":"1","url":"/groups/{group-id}/members/`$ref","id":"2"},{"body":{"subject":"Welcome Meeting","attendees":[{"emailAddress":{"address":"johndoe@example.com","name":"John Doe"},"type":"required"}],"end":{"dateTime":"2025-02-26T10:00:00","timeZone":"Pacific Standard Time"},"body":{"contentType":"HTML","content":"Welcome to the company!"},"start":{"dateTime":"2025-02-26T09:00:00","timeZone":"Pacific Standard Time"}},"method":"POST","headers":{"Content-Type":"application/json"},"dependsOn":"2","url":"/users/`$userId/events","id":"3"},{"body":{"isInsideOrganization":true,"role":"limitedRead","emailAddress":{"address":"johndoe@example.com","name":"John Doe"},"isRemovable":true},"method":"POST","headers":{"Content-Type":"application/json"},"dependsOn":"3","url":"/users/`$userId/calendar/calendarPermissions","id":"4"}]}'
"@


$curlObject2 = Invoke-Curl2PS -CurlString $curlString2
$generatedScript2 = Convert-CurlToPowerShell -CurlObject $curlObject2
$generatedScript2


# Remember to outcomment $ with ` in your curl string
$liveSample = @"

"@


$curlObject3 = Invoke-Curl2PS -CurlString $liveSample
$generatedScript3 = Convert-CurlToPowerShell -CurlObject $curlObject3

# Output the generated script
$generatedScript3
